include/GUnit/GTest.h
Problem:
- Multiple translation units being linked cause a linker
error because ShouldUseColor() is not inlined.
Solution:
- inline ShouldUseColor()
=> [bug] inline ShouldUseColor()

include/GUnit/GTest.h
Problem:
- Test name is also colored.
Solution:
- Color only the 'SHOULD' and 'DISABLED'.
=> [color] Only color the SHOULD, not the test name

include/GUnit/GTest.h
Problem:
- Quickly scanning the output is difficult.
Solution:
- Indent the test name to make it obvious that the `SHOULD`s are
sub-tests.
=> :art: Indent test name and dim disabled tests for readability

include/GUnit/Detail/StringUtils.h, test/Detail/StringUtils.cpp, test/GMake.cpp
Problem:
- Only decimal numbers are allowed to be passed as gherkin parameters.
Solution:
- Add additional parsing for hex parameters.
=> :new: [GSteps] Allow hex numbers in as gherkin parameters

test/GSteps.cpp
Problem:
- On gcc 8.3.0, test/GSteps.cpp:71 fails with "-Werror=ignored-qualifiers".
Solution:
- Static cast to "bool" instead of "const bool".
=> :bug: Fix #29 - test/GSteps.cpp: -Werror build failure on ignored-qualifiers

include/GUnit/GSteps.h, include/formatters/cucumberjson.hpp, include/formatters/features.hpp, include/formatters/gherkinCpp/background.hpp, include/formatters/gherkinCpp/element.hpp, include/formatters/gherkinCpp/feature.hpp, include/formatters/gherkinCpp/genericinfo.hpp, include/formatters/gherkinCpp/scenario.hpp, include/formatters/gherkinCpp/scenariooutline.hpp, include/formatters/gherkinCpp/step.hpp, include/formatters/gherkinCpp/tag.hpp
Pull request would solve issue #34. When executing, instead of having only the variable `SCENARIO=<scenario_path>` the env variable `OUTPUT=json` be added as well, a file "guint_result.json" is created
The classes in formatters/gherkinCpp could be placed into the library gherkin-cpp. I just left it here for now, so it can compile and run all tests.
The part within the ParseAndRegister can also be moved to the gherkin-cpp library in the parser, but again, just left it here to be more easily readable for now and to be able to run all tests.
=> #1 add cucumber json formatter

include/GUnit/GMock.h, test/GMock.cpp
Added std::forward at specific places to move the arguments when
necessary.
This would solve issue #11.
Although all unit-tests run fine, I'm unsure if these changes would have any side effects. E.g. if there are cases where the argument value is still required after invoking the function.
=> Add support for mocking functions with rvalue arguments.

include/GUnit/GTest.h, test/GTest.cpp
This is very helpful if tests for parts of a class should be split up, e.g. for different functions, and require different types of parameters.
The idea is to not only use the type name as suite name but also add the test name.
I'm not sure if something will be broken with it. For some reason also GTest only uses the suite name for GetTestSuitePatternHolder(). However with GTest usually different fixture classes are created. With GUnit only the class to be tested needs to be specified.
=> Allow multiple parameterized tests for a single type.

include/GUnit/GSteps.h, include/formatters/features.hpp
Add the feature tags to the feature key.
Currently if two features have the same name, but different tags (which can have slightly different scenario steps), the feature will not be a different key in the "features" map.
This change will create a new entry in case two features with the same name have different tags.
=> #5 Added tag names as key for feature in features map

README.md
Change first example code to use the correct fixture name in the TEST_F macro invocations.
Fixes #43
=> :books: [README] Fix typo in first Motivation example

include/GUnit/GTest-Lite.h
Problem:
- For `_test` and `_test_disabled` UDLs, their reference to `detail`
namespace may be ambiguous. This would be the case if including this
header file and also having a `using namespace` directive for a
namespace which it itself has a `detail` namespace.
Solution:
- Avoid namespace ambiguity by prefixing with `::` when referring to
`detail` namespace.
=> :bug: Namespace ambiguity with detail

CMakeLists.txt, README.md, include/GUnit/GAssert.h, test/GAssert.cpp
Problem:
- EXPECT_EQ/ASSERT_EQ and friends aren't very easy to use and there are
different overloads based on types.
Solution:
- Introduce EXPECT(...)/ASSERT(...) which uses natural way of expressing logic.
=> :new: [GAssert] EXPECT/ASSERT without special cases

CMakeLists.txt, example/GAssert.cpp, include/GUnit/GSteps.h
Problem:
- There are no examples for ASSERT/EXPECT.
Solution:
- Add GAssert examples.
=> :new: [example] GAssert example

example/GAssert.cpp, include/GUnit/GAssert.h, include/GUnit/GSteps.h, test/GAssert.cpp
Problem:
- EXPECT/ASSERT doesn't work properly with single boolean expression
which is not followed by an operator.
Solution:
- Add logic in the comp destructor to recognise this use case and fire if needed.
=> :bug: [EXPECT/ASSERT] Fix support for boolean expression

CMakeLists.txt, include/GUnit/GAssert.h
In our project we still are on CXX 14 and if GUnit would force CXX-17 we wouldn't be able to use it, except with a fork we would have to maintain on our own.
Could you please consider using CXX 14 as a default for the project?
We are using GUnit with the CXX 14 hacked into, and it works pretty well. So the only change was this most recent patch introducing std::size() from CXX 17.
=> Request to set CXX-14 instead of CXX-17 as a minimum required version

CMakeLists.txt, README.md
This PR is using the gherkin-cpp with the new CMake integration!
It was developed using add_subdirectory but the installation with a STAGING_DIR and ExternalProject_Add is also supported but not as well documented.
This build works with make and ninja!
=> Added gunit INTERFACE target, integrated gherkin-cpp via CMake

include/GUnit/GMock.h
Just to get rid of plain C casts and a small type mismatch. No functional change.
=> addresses some compiler warnings

include/GUnit/GAssert.h
Problem:
- `EXPECT(foo, bar)` doesn't do what's expected but compiles fine.
Solution:
- Add a function that only takes one argument and use that in an
uninvoked context and ensure that the arg pack satisfies that
function.
=> :bug: Warn if EXPECT or ASSERT gets more than one parameter

CMakeLists.txt, include/GUnit/Detail/ProgUtils.h, include/GUnit/GSteps.h
I had to change the delimiter of the tags in the testname for the GStesps. Somehow the comma was not working in Windows, and only one test would be executed within a feature file.
=> Add MSVC support

include/GUnit/Detail/TypeTraits.h, include/GUnit/GMock.h, include/GUnit/GTest.h, test/Detail/TypeTraits.cpp
In this PR I have updated to googletest 1.12.1
Additionally I have fixed some smaller findings, especially regarding clang:
- added: `// NOLINT` to ignore findings for 
-clang-analyzer-core.NonNullParamChecker
-clang-analyzer-core.CallAndMessage
- fixed: unit test using `get_type_name()` may not contain inline namespace `v1::`
- fixed: using `static_cast` to avoid -Wold-style-cast compiler warning
=> Support googletest 1.12.1

include/GUnit/GSteps.h
Problem:
Working with BDD tests can be challenging in large repositories
because it is difficult to find the implementation of steps. Patterns
of text substitution and multi-line strings make simple greps for step
definitions insufficient.
Solution:
Rather than outputting either the step location or the feature file
location, we will instead output the feature file location and
optionally the step definition location if available (uses $Given,
$When, $Then)
=> :technologist: Output path to feature file and source for steps

include/GUnit/GTest.h
Problem:
Build issues when using `-Wshadow` and a variable `sut` is used in a named test case.
Solution:
Add a template specialization for `GTest` with name as type. Omit the sut variable here.
=> Remove sut member variable from named test cases.

CMakeLists.txt
Added environment variables to test registration.
So when the test is run using CTest it will actually run the tests using the defined scenario.
This will enable the use of CTest without needing to redefine the SCENARIO variable.
Making it possible for test explorers to run the test
=> Added environment variables to test registration

CMakeLists.txt
Removed running custom command.
This command causes the test to run at build, possibly stopping the build process if any test fails.
=> Removed custom command

include/GUnit/GMock.h
Just a one liner to silence a Clang -Wdeprecated-this-capture warning
=> Silence -Wdeprecated-this-capture warning

include/GUnit/GAssert.h, test/GAssert.cpp
Problem:
- logical expressions fail in `EXPECT()` and `ASSERT()` because of operator precedence
Solution:
- wrap `__VA_ARGS__` use in macros with an extra set of parens
=> :sparkles: enable support for logical expressions in EXPECT and ASSERT

include/GUnit/GTest.h
Problem:
- GTest.h uses constructs from `std::` without including them; in later versions of GoogleTest they are not necessarily transitively included.
Solution:
- Add includes for:
- `iomanip` (`std::left`, `std::setw`)
- `iostream` (`std::cout`, `std::endl`)
- `tuple` (`std::tie`)
- `type_traits` (various e.g. `std::is_same`)
=> :bug: Fix std includes for `GTest.h`

.github/workflows/macos.yml, .github/workflows/windows.yml
By default, the macOS and Windows GitHub workflows all use the `ubuntu-latest` runner, meaning that all of the tests run on an Ubuntu environment, not Windows or macOS. These changes fix that such that the right runners are chosen to run the tests on the right operating systems.
There are [failures caught on macOS and Windows](https://github.com/divark/GUnit/actions) from the library itself in doing this. I recommend making separate PRs to address these issues.
=> CI: Fix Windows and macOS workflows to use correct runners
